### ISSUE TITLE
Content Request: calling third-party APIs using HttpClient and Refit

### ISSUE THREAD

**Issue by springcomp** [marcduiker/azure-functions-university#149]
I have material for covering the following subjects:

- How to use Refit to represent a third party REST API with interfaces.
- How to make use of dependency injection to benefit from automatically built proxies.
- How to include custom authentication / bearer token injection into every outgoing HTTP request.
- How to customize logging

I plan to start from the HttpTrigger lesson that seems to be the ideal previous step for this lesson.
I may need to familiarize myself with the various idiosyncracies of this repo (CodeTour, etc.).

**Comment by marcduiker** [comment]
Thanks for submitting this! I really like a lesson on this topic! 

Q: Will it use .NET 6 based functions that uses a Program.cs to configure the DI?

I can help you with the workspace and CodeTour bits. Preparing an outline for the lesson and writing all the exercises is the most important part. 

Tip: try to keep the content manageable so it can be presented in +/- 45 minutes.

**Comment by springcomp** [comment]
If you’d like we can make some tests and you will know if that’s OK for me to co-host a live presentation.

As much as possible, yes, I’d like to use .NET 6-based functions. However, I’m not sure I know how to forego the `Startup.cs` for dependency injection. If you have an example of that, I would definitely like to tend towards this. I’ll try and dig a sample on my end as well.

Please, let me take some time to write a first draft for the lesson and excercises and we can initiate some feedback.

**Comment by marcduiker** [comment]
Sounds good! :) 

Here are some .NET (isolated) samples:
https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#start-up-and-configuration

and samples: https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/Extensions
Check the `program.cs` file and the DependencyInjection folder.

No rush, take your time, and I'm happy to jump on a call later to discuss things in more detail.

**Comment by springcomp** [comment]
@marcduiker I just created #151.

Maybe this is a bit premature but I do not know how you’d like to initiate feedback.

**Comment by marcduiker** [comment]
@springcomp Can we connect on Twitter so we can discuss the recording/streaming of the lesson? https://twitter.com/marcduiker
