### ISSUE TITLE
Content Request: Python Azure Functions intro

### ISSUE THREAD

**Issue by vrdmr** [marcduiker/azure-functions-university#15]
## 📝 Lesson Description

_Provide a clear and concise description of the content you'd like to have included._

I would love to see and contribute to the Azure Functions University to showcase Python Functions. Python has been growing in usage and it does need its own intro and some bindings tutorial.

## Are you authoring the lesson? 

✍ _Indicate if you want to (help) write the lesson._

Yes

👩‍🏫 _If you are authoring then indicate if you want to join our live stream to help teach this lesson._ 

Yes.

---

Thanks! 😃 That's all we need to know for now. If you're interested in writing the lesson yourself please read the __Process__ and __Lesson Structure__ parts below so you're well prepared! 💪

---

### Process

If you are contributing to create a lesson, please take into account the length and the tone of the existing lessons. We want to have a uniform experience across all of our lessons.

Once we've discussed this issue and agree to include the lesson you can submit a PR with the lesson and the source code. It will probably take a few iterations to get everything right, don't feel discouraged by this process ♥.

### Lesson Structure

Please keep in mind the following structure of a lesson:

- Give the lesson a short but descriptive title.
- Describe the goal of the lesson.
- Break up the lesson in small exercises.
- Each exercise has a clear sub goal and steps how to achieve that sub goal.
- Use code samples and plenty of 📝, 🔎 and ❔ call-outs.
- Add a new project to the `src` folder with a completely worked out example.

**Comment by atul-ram** [comment]
i am interested and would like to explore/contribute to this area

**Comment by marcduiker** [comment]
Hi @vrdmr, yes I totally agree on thisssss 🐍😉.

It would be great if you could start with the [Prerequisites](https://github.com/marcduiker/azure-functions-university/blob/main/lessons/prerequisites.md) and the [HTTP Trigger lesson](https://github.com/marcduiker/azure-functions-university/blob/main/lessons/http.md) and 'translate' these to Python. Once these are in place you definitely continue with the other lessons, but we should also encourage others to contribute to make these translations 😊.

We should strive to maintain the structure of the existing lessons as much as possible. Let's also try to keep the function names and classes exactly the same so the [test files](https://github.com/marcduiker/azure-functions-university/tree/main/test) can be re-used. 

I suggest `lessons/prerequisites-python.md` and `lessons/http-python.md` as the filenames. We can add language subfolders inside the `src` folder, so we have `src/python`, `src/typescript` and `src/dotnet` etc. What do you think?

**Comment by lechnerc77** [comment]
Should we also do the same for other supported languages like JavaScript/TypeScript?

**Comment by marcduiker** [comment]
> Should we also do the same for other supported languages like JavaScript/TypeScript?

Yes, that would be great! Feel free to create an issue specific for JS/TypeScript if you want to contribute on those 😁.

**Comment by vrdmr** [comment]
@marcduiker Sounds good! :)

>It would be great if you could start with the Prerequisites and the HTTP Trigger lesson and 'translate' these to Python. Once these are in place you definitely continue with the other lessons, but we should also encourage others to contribute to make these translations 😊.

I'll get the first ones started and will send in a PR.

>We should strive to maintain the structure of the existing lessons as much as possible. Let's also try to keep the function names and classes exactly the same so the test files can be re-used.

I agree and will follow the same names for the App and Functions names.

>I suggest lessons/prerequisites-python.md and lessons/http-python.md as the filenames. We can add language subfolders inside the src folder, so we have src/python, src/typescript and src/dotnet etc. What do you think?

I would love to see runtime (language) specific folders. I would add the version as well, to be very clear on what version of python is this training targeted on, and we can call out if there are any specific changes that can hit if folks are not using the specific version. Let me know if this is a good idea.

**Comment by marcduiker** [comment]
@vrdmr yes, good idea to include the runtime version as part of the folder name! I'll make the changes for the .NET Core sources.

**Comment by marcduiker** [comment]
The first lesson (Http trigger) has been picked up by @Dzvezdana. Closing this umbrella issue in favor of having separate issues for each specific topic (e.g. Queue, Table etc.)
