### ISSUE TITLE
Content Request: From Functions to Durable Functions

### ISSUE THREAD

**Issue by lechnerc77** [marcduiker/azure-functions-university#2]
## 📝 Lesson Description

This lesson should demonstrate how to move from a Azure Functions that contains several steps that need to be executed in sequence to a resilient and maintainable setup making use of durable functions. 

- The starting point of the journey is a single Azure Function that executes two downstream calls to a 3rd party system. The second call depends on the result of the first call. Based on this the shortcomings of this approach are highlighted
- Introduction to Durable Functions as an extension to Azure Functions that enables to overcome the above discussed shortcomings
- Refactoring of the single Azure Function to a Durable Function namely a sequence of two calls via activities
- Increase robustness by introducing
   - Retry policies
   - Timeouts

Optional part (or maybe separate session)
- Introduction to Durable Entities
- Usage of Durable Entities to model a circuit breaker in the scenario of the downstream calls

If you want to take a closer look at the content, here are two blog posts going more into detail:
- Description of the overall scenario: [A Serverless Extension Story – From ABAP to Azure](https://blogs.sap.com/2019/12/09/a-serverless-extension-story-from-abap-to-azure/)
- Description of the refactoring: [A Serverless Extension Story II – Bringing State to the Stateless](https://blogs.sap.com/2020/02/17/a-serverless-extension-story-ii-bringing-state-to-the-stateless/)

## Are you authoring the lesson? 

YES (Important to mention: the example would be in TypeScript) 

👩‍🏫 _If you are authoring then indicate if you want to join our live stream to help teach this lesson._ 

YES (Important to mention: the example would be in TypeScript)

---

Thanks! 😃 That's all we need to know for now. If you're interested in writing the lesson yourself please read the __Process__ and __Lesson Structure__ parts below so you're well prepared! 💪

---

### Process

If you are contributing to create a lesson, please take into account the length and the tone of the existing lessons. We want to have a uniform experience across all of our lessons.

Once we've discussed this issue and agree to include the lesson you can submit a PR with the lesson and the source code. It will probably take a few iterations to get everything right, don't feel discouraged by this process ♥.

### Lesson Structure

Please keep in mind the following structure of a lesson:

- Give the lesson a short but descriptive title.
- Describe the goal of the lesson.
- Break up the lesson in small exercises.
- Each exercise has a clear sub goal and steps how to achieve that sub goal.
- Use code samples and plenty of 📝, 🔎 and ❔ call-outs.
- Add a new project to the `src` folder with a completely worked out example.

**Comment by marcduiker** [comment]
Hi @lechnerc77, thank you for your this content request! Durable Functions is a great topic (my fav 😊) and I suggest we work together on this so you can prepare the material for TypeScript and I can prepare it for C#. 

I like the idea of moving from basic functions to a sample where DF is used. Let's keep this lesson only for function chaining (and the theory of clients, orchestrators and activities). Other patterns can be done in separate lessons so we can keep them small and understandable. 

I suggest you start with the work inside a `lessons\DurableFunctions\chaining.md` file, the the sources in `src\DurableFunctions\TypeScript\`.

I consider this a slightly advanced topic so we'll push this into the new year. This gives us plenty of time to prepare the content😊.

**Comment by lechnerc77** [comment]
Hi @marcduiker, 
sounds good (especially the plenty of time part 😊). I will do as proposed and keep you updated with the progress. 
Shall I raise two more issues for the other patterns (retry and timeout) as well as for durable entities?

**Comment by marcduiker** [comment]
Great! I think we can include the retry/timeout part as chapters within the lesson. But other DF application patterns, such as fan-out/fan-in, monitor, human interaction, entities, should be treated as separate lessons.

**Comment by lechnerc77** [comment]
Ah misunderstanding from my side - now I got you. Makes perfect sense to have dedicated sessions on the other patterns you mentioned. Then I will structure my session accordingly

**Comment by marcduiker** [comment]
Lesson content is merged 🎉
