### ISSUE TITLE
Question:  Program.cs template 

### ISSUE THREAD

**Issue by taljundi** [marcduiker/azure-functions-university#202]
### 📚 Lesson Name

Calling third-party REST APIs

### 💬 Lesson Language

- [X] .NET Core
- [X] .NET 5
- [ ] PowerShell
- [ ] TypeScript

### 🤸 Lesson Exercise Number

2

### 📝 Question

The new dotnet 6 template does not have the Main method, so I have two questions please

1- Is it possible to update the steps so that it reflects the program.cs as per the new template
2- Do we have to implement DI as per this guide: 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#prerequisites

**Comment by marcduiker** [comment]
Thanks for raising this @taljundi! We will update the lesson so this is not confusing.

Regarding DI, the link you're referring to is still relevant for .NET Core 3.1/.NET5 functions and .NET6 **in-process** functions. The current . NET6 lessons are based on **out-of-process** (more info [here](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide)) and **does not** use that DI implementation any longer. I think I need to make a lesson soon on the different models (in-process vs out-ot-process) to make that clearer.

@springcomp could you look into clarifying the lesson (and perhaps updating the code)? I noticed as well that the .NET 6 function template (using VSCode) does not use a namespace and class definition any longer for the Program.cs file. We could link to the full [Program.cs](https://github.com/marcduiker/azure-functions-university/blob/main/src/dotnet6/http-refit/AzFuncUni.Http/Program.cs) file if we can't avoid a namespace/class definition.

**Comment by springcomp** [comment]
@marcduiker @taljundi would you like the code and corresponding reference in the lesson to match that of my [currently pending PR](#189) ?

**Comment by marcduiker** [comment]
@springcomp yes, that looks good!

**Comment by marcduiker** [comment]
Thanks for fixing this @springcomp !
