### ISSUE TITLE
VScode debugger

### ISSUE THREAD

**Issue by gallettoNL** [marcduiker/azure-functions-university#26]
## 📝 Question
Hi,

I'm new to VS Code, and in lesson 1 I get stuck on getting the debugger up.
When I hit F5, this is what appears:

Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell, --custom]
Haven't been able to find anything useful on Stackoverflow and the likes...

Any ideas?

Cheers and dank je wel,

Will de Haan

**Comment by marcduiker** [comment]
Hi Will, when you create an Azure Functions project, a _local.settings.json_ file should be created as well. Do you have that file? And if so, does it contain this key/value pair: `"FUNCTIONS_WORKER_RUNTIME": "dotnet",`

**Comment by gallettoNL** [comment]
Ah, right,
I was debugging the code from the repo directly.
Stanx!

Will de Haan

Van: Marc Duiker <notifications@github.com>
Verzonden: 28 februari 2021 12:28
Aan: marcduiker/azure-functions-university <azure-functions-university@noreply.github.com>
CC: Will de Haan <will@lievestro.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [marcduiker/azure-functions-university] VScode debugger (#26)


Hi Will, when you create an Azure Functions project, a local.settings.json file should be created as well. Do you have that file? And if so, does it contain this key/value pair: "FUNCTIONS_WORKER_RUNTIME": "dotnet",
