### ISSUE TITLE
Content Request: How to manage Connection Strings and Bindings with Azure Functions and CosmosDB

### ISSUE THREAD

**Issue by gmartinezsan** [marcduiker/azure-functions-university#3]
## 📝 CosmosDB Bindings and handling Connection Strings

I suggest a lesson where we go on how to develop Azure Functions that use Input/Output bindings with a Database like CosmosDB and how to configure the connection string when developing locally and then when deploying.

Topics to include:

- Develop your Azure Function using VS Code and Azure Functions extension
- Adding Input bindings for CosmosDB
- Configuring Connection Strings
- Testing locally 
- Deploying

## Are you authoring the lesson? 

✍ _Indicate if you want to (help) write the lesson._

Yes I'm authoring the lesson.

👩‍🏫 _If you are authoring then indicate if you want to join our live stream to help teach this lesson._ 

Yes, I can join.

---

Thanks! 😃 That's all we need to know for now. If you're interested in writing the lesson yourself please read the __Process__ and __Lesson Structure__ parts below so you're well prepared! 💪

---

### Process

If you are contributing to create a lesson, please take into account the length and the tone of the existing lessons. We want to have a uniform experience across all of our lessons.

Once we've discussed this issue and agree to include the lesson you can submit a PR with the lesson and the source code. It will probably take a few iterations to get everything right, don't feel discouraged by this process ♥.

### Lesson Structure

Please keep in mind the following structure of a lesson:

- Give the lesson a short but descriptive title.
- Describe the goal of the lesson.
- Break up the lesson in small exercises.
- Each exercise has a clear sub goal and steps how to achieve that sub goal.
- Use code samples and plenty of 📝, 🔎 and ❔ call-outs.
- Add a new project to the `src` folder with a completely worked out example.

**Comment by marcduiker** [comment]
Hi @gmartinezsan , thank you for this content request! CosmosDB is high on our list so feel free to start with preparing content using the proposed lesson structure right away! You can start by adding a new `cosmosdb.md` file in the `lessons` folder and demo source code in a new `AzureFunctions.CosmosDB` project in `src`.  

I'm thinking of the following exercises as a lesson which covers nearly everything concerning Azure Functions & CosmosDB:
- Running the CosmosDB Emulator
- Using the CosmosDB Output Binding
- Using the CosmosDB Input Binding
- Creating a CosmosDB Trigger function.
- Deployment to Azure

Please let me know how much of this you want to take on. Both @madebygps and myself are happy to help out.

**Comment by SaulBurgos** [comment]
I would suggest 

- Securing your Connection Strings (best practices)

I mean:  azure key vault and others (I don't know if exist others ways).

And 

 - How to reuse connections between functions

I suggest this because once I wrote a function that were connected to MongoDB and I were not reusing the connection between functions and I had a lot of problems because of that.... no body teach this kind of problems :(

**Comment by gmartinezsan** [comment]
hi @SaulBurgos thanks a lot for the suggestions. I definitely agree with the best practices you mentioned. And will look at the reuse of connections.

**Comment by gmartinezsan** [comment]
hi @marcduiker, I can cover them all, but if I have any issue I will let you know ASAP. Thank you!

**Comment by marcduiker** [comment]
Great @gmartinezsan! Let's aim for a first PR review at mid December so we have some time to fine-tune.

**Comment by gmartinezsan** [comment]
Thank you @marcduiker, agree about mid December.

**Comment by marcduiker** [comment]
Lesson is complete so I'm closing this. Thanks again @gmartinezsan!
