### ISSUE TITLE
Content request: Protect your functions without code key

### ISSUE THREAD

**Issue by SaulBurgos** [marcduiker/azure-functions-university#6]
## 📝 Lesson Description

In this lesson you will learn how to protect your azure functions with azure indentity. There are a lots of tutorials about how to use create azure functions using the code key but this is not the correct way. Learn how to protect your azure functions without the code key

## Are you authoring the lesson? 

✍ _Indicate if you want to (help) write the lesson._

No, because I don't know how to do it. I want to learn how to do it

👩‍🏫 _If you are authoring then indicate if you want to join our live stream to help teach this lesson._ 

Yes, I can :) but I will not help too much because I don't know about the topic

---

Thanks! 😃 That's all we need to know for now. If you're interested in writing the lesson yourself please read the __Process__ and __Lesson Structure__ parts below so you're well prepared! 💪

---

### Process

If you are contributing to create a lesson, please take into account the length and the tone of the existing lessons. We want to have a uniform experience across all of our lessons.

Once we've discussed this issue and agree to include the lesson you can submit a PR with the lesson and the source code. It will probably take a few iterations to get everything right, don't feel discouraged by this process ♥.

### Lesson Structure

Please keep in mind the following structure of a lesson:

- Give the lesson a short but descriptive title.
- Describe the goal of the lesson.
- Break up the lesson in small exercises.
- Each exercise has a clear sub goal and steps how to achieve that sub goal.
- Use code samples and plenty of 📝, 🔎 and ❔ call-outs.
- Add a new project to the `src` folder with a completely worked out example.

**Comment by marcduiker** [comment]
Hi @SaulBurgos, thanks for this content request! Security is a very important aspect indeed, so we will definitely do a lesson about this (more than just Azure Identity). I'll put it in the lesson index for a bit later.

**All**
If anyone would like to contribute to this Security topic then please make yourself known in the comments!

**Comment by SaulBurgos** [comment]
Since my last comment, I begin to investigate this topic and I followed some tutorials ...and I finally did  !!!  I have recorded me in this process and I have uploaded my experience.  7 parts of my case study. This is the link:

https://www.youtube.com/watch?v=sMBGQNnna_c&list=PLsWFeoHgznCyB9Od227P14Ehyckzr39l-


I know that I don't manage all the correct concepts and theory of azure and I don't have too much experience but I would like to help you guys with your content.  I believe  that "Azure functions university" will help a lot of people that are starting.

Please check my video (Sorry is in spanish) and tell if works for the content of this topic.

Thanks

**Comment by marcduiker** [comment]
Closed due to inactivity.
