### ISSUE TITLE
CloudQueueMessage from Microsoft.Azure.Storage.Queue is already deprecated

### ISSUE THREAD

**Issue by ArnoldIsHereToday** [marcduiker/azure-functions-university#61]
## 📝 Remark
In lesson _queue-lesson-dotnet_ step 4 uses the type `CloudQueueMessage` and mentions not to use the old type in the namespace `Microsoft.WindowsAzure.Storage.Queue` but it seems `CloudQueueMessage` from the 'new' namespace is also deprecated.

Taken from nuget Microsoft.Azure.Storage.Queue version  11.2.3:

> Deprecated: The package has been deprecated. 
> Alternate package: Azure.Storage.Queues 

Strange thing is: when I use the type from the namespace that is warned *not* to use: the project compiles and works.

**Comment by marcduiker** [comment]
Hi @ArnoldIsHereToday, thanks for raising this issue! The queue lesson does appear to be pointing to the correct NuGet package (`Azure.Storage.Queues`), and the AzureFunctions.Queue project also uses it. But the reference to the namespace in the lesson is incorrect which causes some confusion. I've updated the namespace to `Microsoft.Azure.Storage.Queue`.
