### ISSUE TITLE
Add package-lock.json for TypeScript Durable Function projects

### ISSUE THREAD

**Issue by marcduiker** [marcduiker/azure-functions-university#88]
## Observation

After adding CI builds for the TypeScript projects it showed that the TypeScript Durable Functions builds fail due to missing package-lock.json files:

```
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.
```

Full error @ https://github.com/marcduiker/azure-functions-university/runs/3196092410?check_suite_focus=true

## Fix
Add the missing package-lock.json files.

Optionally restructure the function in the same way as the Blob project

_Could you pick this up @lechnerc77?_

**Comment by lechnerc77** [comment]
Sure, can you assign me to this issue please. I will fix it this weekend

**Comment by lechnerc77** [comment]
Pull request to fix the issue is available: <https://github.com/marcduiker/azure-functions-university/pull/89>
